name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Autenticar no ECR
    - name: Authenticate with ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

    # Construir e enviar a imagem para o ECR
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
        docker push ${{ secrets.ECR_REPOSITORY }}:latest

    # Atualizar o serviço ECS
    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster ${{ secrets.CLUSTER_NAME }} \
          --service ${{ secrets.SERVICE_NAME }} \
          --force-new-deployment
